typography_spectrum: 0.855359287186996
color:
  saturation: 0.3455792150663968
  brandStrength: 0.4086021
  lightness: 0.2922752931327697
  brandColors:
    - '#222222'
    - '#494949'
    - '#5D5D5D'
    - '#DCDCDC'
    - '#ADADAD'
  rhythmicContrast: 0.8824332268080572
github: true
layout_spectrum: 1
author:
  name: Patrick Housen
  email: info@patrickhousen.com
  url: 'http://patrickhousen.com'
name: Patrick's EPAS Blog
url: 'http://epas.patrickhousen.site'
navigation:
  - name: Module 1 - On Listening
    id: 26fc17de-0035-46db-a1f5-5384d1d21874
    type: content
  - name: Personal Projects
    id: 5f7892da-588d-4b3d-ad39-fa2cda4d9c55
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Patrick's EPAS Blog
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff638e15-d348-4787-af6a-4b7c52e040f8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ff638e15-d348-4787-af6a-4b7c52e040f8.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: My sonorous journey throughout the European Postgraduate in Arts in Sound
purpose:
  - type: external
    url: 'http://patrickhousen.com'
    label: Digital Portfolio
  - type: email
    url: 'mailto:info@patrickhousen.com'
    label: Contact me
